version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 3s
      retries: 10
  postgres:
    image: "postgres:15-alpine"
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exposr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10