version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5