apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exposr.fullname" . }}
  labels:
    {{- include "exposr.labels" . | nindent 4 }}
data:
{{- $exposrIngress := list }}
{{- if eq .Values.exposr.ingress.http.enabled true }}
{{- $exposrIngress = append $exposrIngress "http" }}
{{- end }}
{{- if eq .Values.exposr.ingress.sni.enabled true }}
{{- $exposrIngress = append $exposrIngress "sni" }}
{{- end }}
{{- $exposrTransport := list }}
{{- if eq .Values.exposr.transport.ws.enabled true }}
{{- $exposrTransport = append $exposrTransport "ws" }}
{{- end }}
{{- if eq .Values.exposr.transport.ssh.enabled true }}
{{- $exposrTransport = append $exposrTransport "ssh" }}
{{- end }}
  EXPOSR_LOG_LEVEL: "{{ .Values.exposr.logLevel }}"
  EXPOSR_ADMIN_ENABLE: "true"
  EXPOSR_ADMIN_PORT: "9000"
  EXPOSR_ALLOW_REGISTRATION: "{{ .Values.exposr.allowRegistration }}"
  EXPOSR_API_PORT: "8080"
{{- if .Values.exposr.apiUrl }}
  EXPOSR_API_URL: "{{ .Values.exposr.apiUrl }}"
{{- end }}
{{- if eq .Values.exposr.admin.enabled true }}
  EXPOSR_ADMIN_API_ENABLE: "true"
  EXPOSR_ADMIN_API_PORT: "8081"
{{- if .Values.exposr.admin.apiKey }}
  EXPOSR_ADMIN_API_KEY: "{{ .Values.exposr.admin.apiKey }}"
{{- end }}
{{- end }}
  EXPOSR_CLUSTER: "{{ .Values.exposr.cluster.type }}"
  EXPOSR_CLUSTER_KEY: "{{ .Values.exposr.cluster.key }}"
{{- if eq .Values.exposr.cluster.type "udp"}}
  EXPOSR_CLUSTER_UDP_DISCOVERY: "{{ .Values.exposr.cluster.udp.discovery }}"
{{- end }}
  EXPOSR_STORAGE: "{{ .Values.exposr.storage.type }}"
{{- if eq .Values.exposr.storage.type "redis" }}
{{- if .Values.exposr.storage.redis.url }}
  EXPOSR_STORAGE_REDIS_URL: "{{ .Values.exposr.storage.redis.url }}"
{{- end }}
{{- end }}
  EXPOSR_INGRESS: "{{ join "," $exposrIngress }}"
  EXPOSR_TRANSPORT: "{{ join "," $exposrTransport }}"
{{- if eq .Values.exposr.ingress.http.enabled true }}
{{- if .Values.exposr.ingress.http.domain }}
  EXPOSR_INGRESS_HTTP_DOMAIN: "{{ .Values.exposr.ingress.http.domain }}"
{{- end }}
  EXPOSR_INGRESS_HTTP_PORT: "8080"
{{- end }}
{{- if eq .Values.exposr.ingress.sni.enabled true }}
  EXPOSR_INGRESS_SNI_PORT: "{{ .Values.exposr.ingress.sni.port }}"
{{- if .Values.exposr.ingress.sni.cert }}
  EXPOSR_INGRESS_SNI_CERT: "/etc/exposr/ingress/sni/cert/tls.crt"
  EXPOSR_INGRESS_SNI_KEY: "/etc/exposr/ingress/sni/cert/tls.key"
{{- end }}
{{- end }}
{{- if .Values.exposr.transport.maxConnections }}
  EXPOSR_TRANSPORT_MAX_CONNECTIONS: "{{ .Values.exposr.transport.maxConnections }}"
{{- end }}
{{- if eq .Values.exposr.transport.ssh.enabled true }}
  EXPOSR_TRANSPORT_SSH_PORT: "{{ .Values.exposr.transport.ssh.port }}"
{{- if .Values.exposr.transport.ssh.host }}
  EXPOSR_TRANSPORT_SSH_HOST: "{{ .Values.exposr.transport.ssh.host }}"
{{- end }}
{{- if .Values.exposr.transport.ssh.key }}
  EXPOSR_TRANSPORT_SSH_KEY: "{{ .Values.exposr.transport.ssh.key }}"
{{- end }}
{{- end }}
{{- if .Values.exposr.envs }}
{{ toYaml .Values.exposr.envs | indent 2 }}
{{- end }}
