apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exposr.fullname" . }}
  labels:
    {{- include "exposr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "exposr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "exposr.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "exposr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cluster
              containerPort: 1025
              protocol: UDP
            - name: http
              containerPort: 8080
              protocol: TCP
{{- if eq .Values.exposr.admin.enabled true }}
            - name: admin-api
              containerPort: 8081
              protocol: TCP
{{- end }}
            - name: admin
              containerPort: 9000
              protocol: TCP
{{- if eq .Values.exposr.ingress.sni.enabled true }}
            - name: ingress-sni
              containerPort: {{ .Values.exposr.ingress.sni.port }}
              protocol: TCP
{{- end }}
{{- if eq .Values.exposr.transport.ssh.enabled true }}
            - name: transport-ssh
              containerPort: {{ .Values.exposr.transport.ssh.port }}
              protocol: TCP
{{- end }}
          volumeMounts:
            - name: app
              mountPath: /tmp/app
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
{{- if .Values.exposr.ingress.sni.cert }}
            - name: ingress-sni-cert
              mountPath: /etc/exposr/ingress/sni/cert
              readOnly: true
{{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: {{ include "exposr.fullname" . }}-headless
          livenessProbe:
            httpGet:
              path: /ping
              port: admin
          readinessProbe:
            httpGet:
              path: /ping
              port: admin
          envFrom:
            - configMapRef:
                name: {{ include "exposr.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: app
          emptyDir: {}
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- if .Values.exposr.ingress.sni.cert }}
        - name: ingress-sni-cert
          secret:
            secretName: {{ .Values.exposr.ingress.sni.cert }}
{{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
