class CustomError extends Error {
    constructor(code, message) {
        super();
        this.code = `${code}`;
        this.errno = code;
        this.message = message || this.code;
    }
}

export default CustomError;

export const ERROR_TUNNEL_NOT_FOUND = 'TUNNEL_NOT_FOUND';
export const ERROR_TUNNEL_NOT_CONNECTED = 'TUNNEL_NOT_CONNECTED';
export const ERROR_TUNNEL_ALREADY_CONNECTED = 'TUNNEL_ALREADY_CONNECTED';
export const ERROR_TUNNEL_HTTP_INGRESS_DISABLED = 'TUNNEL_HTTP_INGRESS_DISABLED';
export const ERROR_TUNNEL_TRANSPORT_REQUEST_LIMIT = 'TUNNEL_TRANSPORT_REQUEST_LIMIT';
export const ERROR_TUNNEL_TRANSPORT_CON_TIMEOUT = 'TUNNEL_TRANSPORT_CON_TIMEOUT';
export const ERROR_TUNNEL_UPSTREAM_CON_REFUSED = 'TUNNEL_UPSTREAM_CON_RESET';
export const ERROR_TUNNEL_UPSTREAM_CON_FAILED = 'TUNNEL_UPSTREAM_CON_FAILED';
export const ERROR_HTTP_INGRESS_REQUEST_LOOP = 'HTTP_INGRESS_REQUEST_LOOP';
export const ERROR_UNKNOWN_ERROR = 'UNKNOWN_ERROR';
export const ERROR_BAD_INPUT = 'BAD_INPUT';
export const ERROR_AUTH_NO_ACCESS_TOKEN = 'AUTH_NO_TOKEN';
export const ERROR_AUTH_PERMISSION_DENIED = 'PERMISSION_DENIED';
