replicaCount: 1

exposr:
  logLevel: info
  allowRegistration: false
  admin:
    enabled: false
    apiKey: ""
  cluster:
    key: "cluster-signing-key-change-me"
    type: udp
    udp:
      discovery: kubernetes
  storage:
    url: memory:// 
    pgsql: {}
  transport:
    maxConnections: 2
    ws:
      enabled: true
    ssh:
      enabled: false
      port: 2200
      servicePort: 22
      host: ""
      key: ""
  ingress:
    http:
      enabled: false
      domain: ""
    sni:
      enabled: false
      port: 4430
      servicePort: 443
      cert: ""
  envs: {}

image:
  repository: docker.io/exposr/exposrd
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  adminApiPort: 8080
  adminPort: 9000

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

ingressAdmin:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes: []

extraVolumeMounts: []