name: branch
on:
  push:
    branches:
      - '*'
      - '!master'

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          yarn install --frozen-lockfile
          yarn run test test

      - name: Prepare builder
        run: make builder.build

      - name: Build package
        run:  |
            make package.build.container

      - name: Build and smoke test docker image
        run:  |
            make image.build
            docker run --rm -t $(make get.image) --version | grep $(make get.version)
            docker run --rm -t -e EXPOSR_SELF_TEST=1 $(make get.image)