name: helm release
on:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout helm chart repo
        uses: actions/checkout@v3
        with:
          repository: exposr/helm-charts
          path: helm-charts
          token: ${{ secrets.HELM_CHART_REPO_TOKEN }}

      - name: Copy source chart
        run: |
          rm -fr helm-charts/charts/exposr
          cp -rp helm helm-charts/charts/exposr

      - name: Publish chart
        run: |
          cd helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m 'chore: update exposr chart'
          git push
