name: master
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git
        uses: actions/checkout@v3

      - name: Setup builder
        run: make builder.build

      - name: Build package
        run:  |
            make package.build.container

      - name: Save package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist
          retention-days: 1

  dist_macos:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Get package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Extract package
        run:  |
            tar xvf exposrd-*.tgz --strip-components=1

      - name: Build distribution
        run:  |
            make dist.macos.build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-dist
          path: dist
          retention-days: 1

  dist_linux:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Extract package
        run:  |
            tar xvf exposrd-*.tgz --strip-components=1
            mkdir -p dist
            mv exposrd-*.tgz dist/

      - name: Build binary dist files
        run:  |
            make dist.xbuild

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: dist/exposrd-*-linux-*
          retention-days: 1

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish versioned container to ghcr.io
        run:  |
          make publish=true registry=ghcr.io/exposr image.xbuild
          make publish=true registry=ghcr.io/exposr nodist.image.xbuild

      - name: Publish unstable container to ghcr.io
        run: |
          make registry=ghcr.io/exposr image.xbuild.unstable
          make registry=ghcr.io/exposr nodist.image.xbuild.unstable

  summary:
    runs-on: ubuntu-latest
    needs: [dist_linux, dist_macos]

    steps:
      - name: Package artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Linux build artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-dist

      - name: MacOS build artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-dist

      - name: Build summary
        run: |
          ls

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: exposrd-unstable
          path: exposr-*
          retention-days: 7