name: master
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git
        uses: actions/checkout@v2

      - name: Setup builder
        run: make builder.build

      - name: Build package
        run:  |
            make package.build.container

      - name: Save package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist
          retention-days: 1

  dist_macos:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Get package
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Extract package
        run:  |
            tar xvf exposr-server-*.tgz --strip-components=1

      - name: Build distribution
        run:  |
            make dist.macos.build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-dist
          path: dist
          retention-days: 1

  dist_linux:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get package
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Extract package
        run:  |
            tar xvf exposr-server-*.tgz --strip-components=1

      - name: Setup builder
        run: make builder.build

      - name: Build distribution
        run:  |
            make dist.linux.build.container

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: dist
          retention-days: 1

      - name: Log in to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Publish versioned container to hub.docker.com 
        run:  |
          make publish=true image.buildx

      - name: Publish unstable container to hub.docker.com 
        run: |
          make image.buildx.unstable

  summary:
    runs-on: ubuntu-latest
    needs: [dist_linux, dist_macos]

    steps:
      - name: Package artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Linux build artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux-dist

      - name: MacOS build artifacts
        uses: actions/download-artifact@v2
        with:
          name: macos-dist

      - name: Build summary
        run: |
          ls

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: exposr-server-unstable
          path: exposr-*
          retention-days: 7