name: release
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git
        uses: actions/checkout@v3

      - name: Setup builder
        run: make builder.build

      - name: Build package
        run:  |
            make package.build.container

      - name: Save package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist
          retention-days: 1

  dist_macos:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Get package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Extract package
        run:  |
            tar xvf exposrd-*.tgz --strip-components=1

      - name: Build distribution
        run:  |
            make dist.macos.build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-dist
          path: dist
          retention-days: 1

  dist_linux:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Extract package
        run:  |
            tar xvf exposrd-*.tgz --strip-components=1
            mkdir -p dist
            mv exposrd-*.tgz dist/

      - name: Build binary dist files
        run:  |
            make dist.xbuild

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: dist/exposrd-*-linux-*
          retention-days: 1

      - name: Login to hub.docker.com
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Publish versioned container
        run:  |
          make publish=true image.xbuild

      - name: Publish latest container
        run: |
          make image.xbuild.latest

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish versioned container to ghcr.io
        run:  |
          make publish=true registry=ghcr.io/exposr image.xbuild

      - name: Publish latest container to ghcr.io
        run: |
          make registry=ghcr.io/exposr image.xbuild.latest

  release:
    runs-on: ubuntu-latest
    needs: [dist_linux, dist_macos]

    steps:
      - name: Package artifact
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Linux build artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-dist

      - name: MacOS build artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-dist

      - name: Generate SHA256 sums for artifacts
        run: |
          ls exposrd-* | xargs -L 1 -I {} sh -c "sha256sum  {} > {}.sha256"

      - name: Build artifacts
        run: |
          ls

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ startsWith(github.ref, '/refs/tags/v0') }}
          files: |
            exposrd-*
